os:
  - linux
language: nix
nix: 2.3.6
before_install:
  - nix-env -iA nixpkgs.cachix
  - nix-env -f https://github.com/dapphub/dapptools/archive/master.tar.gz -iA solc-static-versions.solc_0_5_12
  - echo "trusted-users = root travis" | sudo tee -a /etc/nix/nix.conf && sudo pkill nix-daemon
  - cachix use maker
script:
  - nix-shell --pure --run 'dapp --use solc:0.5.12 test'
